server:
  port: 8763

spring:
  application:
    name: server-zuul
zuul:
  routes:
    user-server: /api-user/**
    shop-server: /api-shop/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
